version: '3'


volumes:
  failures_local_postgres_data: {}
  failures_local_postgres_data_backups: {}
  failures_local_chroma_data: {}

networks:
  net:
    driver: bridge

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: failures_local_django
    container_name: failures_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
      - chroma
    volumes:
      - .:/app:z
    env_file:
      - .env
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.data
    ports:
      - "8000:8000"
    command: /start
    networks:
      - net


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: failures_production_postgres
    container_name: failures_local_postgres
    volumes:
      - failures_local_postgres_data:/var/lib/postgresql/data:Z
      - failures_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - net


  chroma:
    image: ghcr.io/chroma-core/chroma:1.0.9 #latest
    container_name: failures_local_chromadb
    volumes:
      - failures_local_chroma_data:/var/lib/chroma/data:Z
    ports:
      - "8001:8001"
    expose:
      - 8001
    networks:
      - net
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/var/lib/chroma/data
      - ALLOW_RESET=TRUE
    #command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8001
    command: run --host 0.0.0.0 --port 8001 --path /var/lib/chroma/data
    extra_hosts:
      - "host.docker.internal:host-gateway"


  redis:
    image: redis:6
    container_name: failures_local_redis
    networks:
      - net

  celeryworker:
    <<: *django
    image: failures_local_celeryworker
    container_name: failures_local_celeryworker
    depends_on:
      - redis
      - postgres
      - chroma
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: failures_local_celerybeat
    container_name: failures_local_celerybeat
    depends_on:
      - redis
      - postgres
      - chroma
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: failures_local_flower
    container_name: failures_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  chainlit:
    <<: *django
    image: failures_local_chainlit
    container_name: failures_local_chainlit
    working_dir: /app/failbot
    depends_on:
      - django
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8501:8501"
    command: chainlit run failbotUI.py --port 8501 --host 0.0.0.0 
