version: '3'


volumes:
  failures_local_postgres_data: {}
  failures_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: failures_local_django
    container_name: failures_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia/cuda:11.4.0-base nvidia-smi
    #           count: 1
    #           capabilities: [gpu]


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: failures_production_postgres
    container_name: failures_local_postgres
    volumes:
      - failures_local_postgres_data:/var/lib/postgresql/data:Z
      - failures_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: failures_local_redis

  celeryworker:
    <<: *django
    image: failures_local_celeryworker
    container_name: failures_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: failures_local_celerybeat
    container_name: failures_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: failures_local_flower
    container_name: failures_local_flower
    ports:
      - "5555:5555"
    command: /start-flower