version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_chroma_data: {}

# TODO: security for traefik
services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: failures_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: failures_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: failures_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:6

  chroma:
    image: ghcr.io/chroma-core/chroma:1.0.9
    volumes:
      - production_chroma_data:/var/lib/chroma/data:Z
    expose:
      - "8001"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/var/lib/chroma/data
      - ALLOW_RESET=TRUE
    command: run --host 0.0.0.0 --port 8001 --path /var/lib/chroma/data

  celeryworker:
    <<: *django
    image: failures_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: failures_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: failures_production_flower
    command: /start-flower

  chainlit:
    <<: *django
    image: failures_production_chainlit
    working_dir: /app/failbot
    depends_on:
      - django
      - chroma
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - REDIS_URL=${REDIS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - CHAINLIT_DB_URI=${DATABASE_URL}
    ports:
      - "8501:8501"
    command: chainlit run failbotUI.py --port 8501 --host 0.0.0.0
