# Generated by Django 4.2.13 on 2025-12-15 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainlitThread',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chainlit_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Thread',
                'verbose_name_plural': 'Chat Threads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChainlitStep',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('disable_feedback', models.BooleanField(default=False)),
                ('streaming', models.BooleanField(default=False)),
                ('input', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('generation', models.JSONField(blank=True, default=dict, null=True)),
                ('show_input', models.BooleanField(default=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('indent', models.IntegerField(default=0)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='chat.chainlitthread')),
            ],
            options={
                'verbose_name': 'Chat Step',
                'verbose_name_plural': 'Chat Steps',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChainlitFeedback',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('for_id', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.chainlitstep')),
            ],
            options={
                'verbose_name': 'Chat Feedback',
                'verbose_name_plural': 'Chat Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='ChainlitElement',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('chainlit_key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='chat.chainlitthread')),
            ],
            options={
                'verbose_name': 'Chat Element',
                'verbose_name_plural': 'Chat Elements',
            },
        ),
    ]
