# Generated by Django 4.1.2 on 2022-10-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255, verbose_name="Keyword")),
                (
                    "start_year",
                    models.IntegerField(null=True, verbose_name="Start Year"),
                ),
                ("end_year", models.IntegerField(null=True, verbose_name="End Year")),
                (
                    "searched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Searched at"),
                ),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Queries",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("url", models.URLField(verbose_name="URL")),
                ("published", models.DateTimeField(verbose_name="Published")),
                ("source", models.URLField(verbose_name="Source")),
                ("summary", models.TextField(blank=True, verbose_name="Summary")),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                (
                    "scraped_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Scraped at"),
                ),
                (
                    "search_query",
                    models.ManyToManyField(
                        related_name="articles",
                        related_query_name="article",
                        to="articles.searchquery",
                        verbose_name="Search Query",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("TRANSIENT", "Transient"),
                            ("PERMANENT", "Permanent"),
                            ("INTERMITTENT", "Intermittent"),
                        ],
                        max_length=12,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("INTERNAL", "Internal"), ("EXTERNAL", "External")],
                        max_length=8,
                        verbose_name="Location",
                    ),
                ),
                (
                    "semantics",
                    models.CharField(
                        choices=[
                            ("CRASH", "Crash"),
                            ("OMISSION", "Omission"),
                            ("TIMING", "Timing"),
                            ("VALUE", "Value"),
                            ("ARBITRARY", "Arbitrary"),
                        ],
                        max_length=9,
                        verbose_name="Semantics",
                    ),
                ),
                (
                    "behavior",
                    models.CharField(
                        choices=[("SOFT", "Soft"), ("HARD", "Hard")],
                        max_length=4,
                        verbose_name="Behavior",
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[("SOFTWARE", "Software"), ("HARDWARE", "Hardware")],
                        max_length=8,
                        verbose_name="Dimension",
                    ),
                ),
                ("manual", models.BooleanField(default=False, verbose_name="Manual")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        related_query_name="annotation",
                        to="articles.article",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
            },
        ),
    ]
