# Generated by Django 4.1.3 on 2022-11-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="failure",
        ),
        migrations.RemoveField(
            model_name="article",
            name="search_query",
        ),
        migrations.AddField(
            model_name="article",
            name="failures",
            field=models.ManyToManyField(
                related_name="articles",
                related_query_name="article",
                to="articles.failure",
                verbose_name="Failures",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="search_queries",
            field=models.ManyToManyField(
                related_name="articles",
                related_query_name="article",
                to="articles.searchquery",
                verbose_name="Search Queries",
            ),
        ),
    ]
