# Generated by Django 4.1.3 on 2022-11-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0002_remove_article_failure_remove_article_search_query_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(max_length=255, unique=True, verbose_name="URL"),
        ),
    ]
