# Generated by Django 4.1.3 on 2022-11-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=510, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(max_length=510, unique=True, verbose_name="URL"),
        ),
    ]
