from public_admin.admin import PublicModelAdmin
from public_admin.sites import PublicAdminSite, PublicApp

from failures.articles.models import Article, Incident

class ArticleModelAdmin(PublicModelAdmin):
    list_display = (
        "id",
        "headline",
        "title",
        "scrape_successful",
        "describes_failure",
        "analyzable_failure",
        "published",
        "source",
        "summary",
        #"summary_embedding",
        "system",
        "ResponsibleOrg",
        "ImpactedOrg",
        "time",
        "SEcauses",
        "NSEcauses",
        "impacts",
        "preventions",
        "fixes",
        "phase_option",
        "boundary_option",
        "nature_option",
        "dimension_option",
        "objective_option",
        "intent_option",
        "capability_option",
        "duration_option",
        "domain_option",
        "cps_option",
        "perception_option",
        "communication_option",
        "application_option",
        "behaviour_option",
        "phase_rationale",
        "boundary_rationale",
        "nature_rationale",
        "dimension_rationale",
        "objective_rationale",
        "intent_rationale",
        "capability_rationale",
        "duration_rationale",
        "domain_rationale",
        "cps_rationale",
        "perception_rationale",
        "communication_rationale",
        "application_rationale",
        "behaviour_rationale",
    )
    search_fields = ["id"]

class IncidentModelAdmin(PublicModelAdmin):
    list_display = (
        "id",
        "title",
        "summary",
        #"summary_embedding",
        "system",
        "ResponsibleOrg",
        "ImpactedOrg",
        "time",
        "SEcauses",
        "NSEcauses",
        "impacts",
        "preventions",
        "fixes",
        "phase_option",
        "boundary_option",
        "nature_option",
        "dimension_option",
        "objective_option",
        "intent_option",
        "capability_option",
        "duration_option",
        "domain_option",
        "cps_option",
        "perception_option",
        "communication_option",
        "application_option",
        "behaviour_option",
        "phase_rationale",
        "boundary_rationale",
        "nature_rationale",
        "dimension_rationale",
        "objective_rationale",
        "intent_rationale",
        "capability_rationale",
        "duration_rationale",
        "domain_rationale",
        "cps_rationale",
        "perception_rationale",
        "communication_rationale",
        "application_rationale",
        "behaviour_rationale",
        "get_articles",
    )
    search_fields = ["title"]

public_app = PublicApp("failures", models=("Article", "Incident"))
public_admin = PublicAdminSite("dashboard", public_app)
public_admin.register(Article, ArticleModelAdmin)
public_admin.register(Incident, IncidentModelAdmin)