#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

/usr/local/bin/gunicorn --workers 3 --timeout 120 config.wsgi:application --bind 0.0.0.0:8000 --chdir=/app
